### ISSUE TITLE
Check/tick icon is not the same as in checkbox component

### ISSUE THREAD

**Issue by elioqoshi** [ubuntu/yaru.dart#797]
The check icon in the Yaru icon set is not the same used as in the checkbox component:

<img width="444" alt="grafik" src="https://github.com/ubuntu/yaru/assets/5436686/b45592a3-de75-4414-a288-678a02f42995">

The checkbox component uses the default material design check icon I assume.
<img width="172" alt="grafik" src="https://github.com/ubuntu/yaru/assets/5436686/74c909a5-34db-46d0-a8a5-f70d327d31c3">

I'd recommend unifying them. So either use the Yaru icon in the checkbox or the Material Design icon in Yaru. The Yaru check/tick icon is rather thin though so I am worried about legibility on a small space like 16x16.

**Comment by elioqoshi** [comment]
@Jupi007 

If they are 33% bigger and the line width is the same that means that the line width is also respectively different, so the icons are not the same.

The icons should have the same scaling line-width regardless of size.

**Comment by Jupi007** [comment]
If we scale the checkbox checkmark stroke width, it results in `1.25px`:

![image](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/738d19c7-a3fb-477f-8886-537d898afb5d)

This looks fuzzy and really not readable.

On the other hand, if we scale the icon to fit the widget, it results in a bold `2.4px` stroke width which looks out of place and inconsistent because it doesn't fit at all to our thin `1.0px` icon look 🤔

The `2.0px` stroke width used for the checkbox checkmark on the `YaruCheckbox` widget is really an exception, because draw a thin white line on an orange surface is very hard to legibly read as you can see on my screenshot upper.

Both the icon in `yaru_icons` and the checkbox checkmark in `yaru_widgets` have different purposes, and I don't think we can simply scale one to fit the other without facing some other problems, which imo are more problematic than the one you point out in this issue.

_Note that if you absolutely think we should do this perfect fit scale, I wouldn't oppose it. If so I think we should make the icon bolder to avoid accessibility problems with the checkbox._

**Comment by Jupi007** [comment]
Closing this, see my comment upper for the explanation.
